### ISSUE TITLE
Sub-optimal results

### ISSUE THREAD

**Issue by Orum** [benjft/ScanSolver3#1]
I've noticed that quite a few of the results have orbits that appear to be, at best, sub-optimal, and at worst, will leave you in an orbit that won't even fully map the body you're orbiting.  The crux of the issue is that the periapsis may fall below the minimum range of the scanners selected.  While this isn't always a barrier to fully scanning a body, it can be, e.g. if the argument of periapsis is 90 or close to it.

It could also be quite bad in other scenarios, even when the argument of periapsis is close to 0.  For example, when using scans that require daylight, if the periapsis is on the 'lit' side of the body, you'll could have to wait quite a while (roughly half a year, in the worst case) to fully complete those scans, assuming the Pe is below the minimum distance.

**Comment by benjft** [comment]
> I've noticed that quite a few of the results [...] will leave you in an orbit that won't even fully map the body you're orbiting

Can you give me an example configuration (scanner & body) for which this happens?

>  The crux of the issue is that the periapsis may fall below the minimum range of the scanners selected. 

Scanning is designed to only occur on the apoapsis side of the orbit as this is where it is most efficient. I don't assume scanning for the entire orbit due to some scanners requiring daylight to function - which they will only have for half the orbit. It also keeps the maths simpler as the tracks aren't crossing weirdly. The scanner will be kept within its functional altitude range between the poles and the apoapsis.

>  For example, when using scans that require daylight, if the periapsis is on the 'lit' side of the body, you'll could have to wait quite a while

Yes. So don't do that.

**Comment by benjft** [comment]
> While this isn't always a barrier to fully scanning a body, it can be, e.g. if the argument of periapsis is 90 or close to it.

From the README:

> The orbit should be established with an **argument of periapsis or 0 or 180 degrees** (0 or pi radians), and the **apoapsis on the sunny side of the orbit** (if sunlight is required to complete any of the scans).

The program works only if these requirements are met.

The argument of periapsis is required as there are assumptions about how the planet is rotating relative to the satellite, and how this affects the area scanned. We want the apoapsis above the equator as this allows us to scan more area with each orbit than would otherwise be possible.

If you want information on why this is the case I can try to find my notes on the maths and talk you through it but in the meantime RTFM

**Comment by Orum** [comment]
Okay.  I guess I just have different objectives in my scanning (minimizing delta-V) compared to what orbits this spits out (minimizing scan time irrespective of how much delta-V it requires to get there).

**Comment by benjft** [comment]
It doesn't minimise delta-v as it's never clear what that means for a given satellite. If it's scanning kerbin then that's a low orbit, but for other bodies that may be a higher orbit. but at the same time, maybe aerobraking means a high eccentricity orbit is best. It's not a simple question to answer without a lot more context than this is trying to understand. This will give you a range of orbits if there are multiple solutions, so choose the highest/lowest and most/least eccentric as applicable to your problem.

The descriptor for this program is exactly what it does though:

>This is a tool created for use with Kerbal Space Program and the [SCANsat](https://github.com/S-C-A-N/SCANsat) mod. It was created to answer the question
>>    "What orbit will complete a surface scan in the shortest time?"
